### ISSUE TITLE
MSVC package: consider using of source distribution

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gnucobol-3.1.2-binaries#2]
Currently it uses a git checkout:

https://github.com/mridoni/gnucobol-binaries/blob/ab58b732bb67775ccbf0c89f100011b5e13275b2/.github/workflows/build-gnucobol-3.1.2-windows-msvc.yml#L30-L33

and therefore has to run quite some steps:

https://github.com/mridoni/gnucobol-binaries/blob/ab58b732bb67775ccbf0c89f100011b5e13275b2/.github/workflows/build-gnucobol-3.1.2-windows-msvc.yml#L54-L81

and misses some of the docs in the end.

I suggest to change that to use the official source package; for 3.1.2 you'll find that at https://ftp.gnu.org/gnu/gnucobol/windows as .zip or .7zip; for the current 3.2-rc1 at https://alpha.gnu.org/gnu/gnucobol.

This would also allow signature check (optional) and to remove:

```diff
-         choco install -y winflexbison3
-         powershell build_windows\maketarstamp.ps1 > tarstamp.h
-         copy build_windows\config.h.in build_windows\config.h
          copy ${{env.VCPKG_ROOT}}\installed\x64-windows\include\db.h build_windows\db.h
-         sed -i 's/3\.1\.1\-dev/3\.1\.2/' build_windows\config.h
          sed -i 's/#define\ CONFIGURED_ISAM\ *VBISAM/#define\ CONFIGURED_ISAM\ BDB/' build_windows\config.h
          sed -i 's/#define\ CONFIGURED_XML\ *NOXML/#define\ CONFIGURED_XML\ XML2/' build_windows\config.h
          sed -i 's/#define\ CONFIGURED_JSON\ *NOJSON/#define\ CONFIGURED_JSON\ CJSON_LOCAL/' build_windows\config.h      
          sed -i 's/"libcharset"/"charset"/' build_windows\config.h
          sed -i 's/"libiconv"/"iconv"/' build_windows\config.h
          sed -i 's/"libintl\.dll"/"intl\.dll"/' build_windows\makedist.cmd
          sed -i 's/"libiconv\.dll"/"iconv\.dll"/' build_windows\makedist.cmd
          sed -i 's/"libcharset\.dll"/"charset\.dll"/' build_windows\makedist.cmd
          sed -i 's/"lzma\*\.dll"/"liblzma\.dll"/' build_windows\makedist.cmd
          sed -i 's/"iconv"/"iconv\-2\.dll"/' build_windows\makedist.cmd         
          sed -i 's/2019\ 2017/2022\ 2019\ 2017/' build_windows\gcvsvars.cmd
-         win_bison -o "cobc\parser.c" "cobc\parser.y"
-         win_bison -o "cobc\ppparse.c" "cobc\ppparse.y"
-         win_flex -o "cobc\pplex.c" "cobc\pplex.l"
-         win_flex -o "cobc\scanner.c" "cobc\scanner.l"  
```

**Comment by mridoni** [comment]
Done with the latest releases (`*-20230124`)

**Comment by GitMensch** [comment]
Nice. You _may_ want to edit https://github.com/mridoni/gnucobol-binaries/releases/tag/3.2rc1-20230124, marking it as pre-release.

**Comment by mridoni** [comment]
> Nice. You _may_ want to edit https://github.com/mridoni/gnucobol-binaries/releases/tag/3.2rc1-20230124, marking it as pre-release.

Done
